# Generated by Django 4.2.3 on 2023-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='product',
        ),
        migrations.AddField(
            model_name='field',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
