# Generated by Django 4.2.3 on 2023-08-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_order_created_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='value',
        ),
    ]
